Vizid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from display import views as dis_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dis_view.home,name="index"),
    path('section/', dis_view.SectionView.as_view(),name="section"),
    path('section/<pk>', dis_view.SectionDetails.as_view(),name="sub_section"),
    path('about/', dis_view.about,name="about"),
    path('contact/', dis_view.contact,name="contact"),

]

if settings.DEBUG==False:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

display/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Section(models.Model):
    section = models.CharField(max_length=50)
    info = models.CharField(max_length=150)
    img = models.ImageField(upload_to="section")

    def __str__(self):
        return self.section


class Sub_section(models.Model):
    sec = models.ForeignKey(Section, on_delete=models.CASCADE)
    info = models.TextField(max_length=150)
    img = models.ImageField(upload_to="sub-section")


class Comment(models.Model):
    name = models.CharField(max_length=50)
    comment = models.TextField()

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=50)
    message = models.TextField(max_length=500)

    def __str__(self):
        return self.email

class Meeting(models.Model):
    name=models.CharField(max_length=50)
    email = models.EmailField()
    phone= models.CharField(max_length=11)
    date = models.DateField()
    reason=models.TextField(max_length=100)

    def __str__(self):
        return self.phone

display/forms.py
from django import forms
from .models import Comment,Contact,Meeting



class UserCommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['name','comment']

class UserContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields=['name','email',"phone","message"]

class UserMeetingForm(forms.ModelForm):
    date=forms.DateField(widget=forms.DateInput(attrs={"type":"date"}))
    class Meta:
        model=Meeting
        fields=['name','email',"phone","date","reason"]

display/views.py
from django.shortcuts import render, redirect
from .models import Section as Sect
from django.views.generic import ListView, DetailView, CreateView
from .models import Comment
from .forms import UserCommentForm,UserContactForm,UserMeetingForm

global context
comment = Comment.objects.all()
context = {"comment": comment}


def home(request):
    comment = Comment.objects.all()

    if request.method=='POST':
        former=UserCommentForm(request.POST)
        if former.is_valid():
            former.save()
            return redirect("display/about.html")
    else:
        former = UserCommentForm()
    context = {"comment": comment,"former":former}
    return render(request,"display/index.html",context)

def about(request):
    return render(request, "display/about.html", context)


def contact(request):
    if request.method=='POST':
        form=UserContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("contact")
    else:
        form = UserContactForm()

    if request.method == 'POST':
        mform=UserMeetingForm(request.POST)
        if mform.is_valid():
            mform.save()
            return redirect("contact")
    else:
        mform = UserMeetingForm()
    return render(request, "display/contact.html",{"former":form,"mform":mform})




class SectionView(ListView):
    model = Sect
    template_name = "display/section.html"
    context_object_name = "section"


class SectionDetails(DetailView):
    model = Sect
    template_name = "display/sectiondetails.html"

display/templates/display/sectiondetails.html
<!DOCTYPE html>
<html class="no-js">
    <head>
        {%load static%}
        <!-- Meta Tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Vizid Decos</title>
        <meta name="description" content="A Template by Vizid"/>
        <meta name="keywords" content=""/>
        <meta name="author" content="Vizid"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="fab/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
       <!--  <link rel="shortcut icon" href="assets/img/favicon.ico" type="image/x-icon">  -->
        <link rel="icon" type="image/x-icon" href="{%static 'display/img/fav.jpg'%}">

        <!-- Web Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'/>
        <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,300,500,700' rel='stylesheet' type='text/css'/>

        <!-- Css Global Compulsory -->
        <link rel="stylesheet" href="{%static 'display/css/bootstrap.min.css'%}" />

        <!-- Css Implementing Plugins -->
        <link rel="stylesheet" href= "{%static 'display/css/font-awesome.min.css'%}" />
        <link rel="stylesheet" type="text/css" href="{%static 'display/css/revolution/style.css'%}" media="screen"/>
        <link rel="stylesheet" type="text/css" href="{%static 'display/css/revolution/extralayers.css'%}"media="screen"/>
        <link rel="stylesheet" type="text/css" href= "{%static 'display/css/revolution/settings.css'%}" media="screen"/>
        <link rel="stylesheet" href= "{%static 'display/css/owl.carousel.css'%}"  />
        <link rel="stylesheet" href="{%static 'display/css/owl.theme.css'%}" />
        <link rel="stylesheet" href="{%static 'display/css/cubeportfolio.min.css'%}" />
        <link rel="stylesheet" href="{%static 'display/css/jquery.mmenu.css'%}" />

        <!-- Css Theme -->
        <link rel="stylesheet" href= "{%static 'display/css/style.css'%}">
    </head>

 <body>

        <!--Start Preloader-->
        <div id="preloader">
            <div class="preloader-container">
                <div class="spinner">
                    <div class="bounce1"></div>
                    <div class="bounce2"></div>
                    <div class="bounce3"></div>
                </div>
            </div>
        </div>
        <!--End Preloader-->

        <!-- Navbar -->
        <nav class="navbar navbar-default header-nav" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Logo -->
                    <a class="navbar-brand" href="index.html"><img src="{%static 'display/img/logo.jpg'%}" class="img-responsive" alt="VizidDecos"></a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"><a href="{%url 'index'%}">Home</a></li>
                        <li><a href="{%url 'about'%}">About</a></li>
                       <!-- <li><a href="#projects">Projects</a></li>     -->
                       <li><a href="{%url 'section'%}">Products</a></li>
                       <li><a href="{%url 'contact'%}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Navbar -->



        <!-- Site Wrapper -->
        <div class="container padding-bottom padding-top-x2" id="projects">
                <div class="row">

                    <!-- Section General Title -->
                    <div class="general-title text-center">
                        <h2>{{object.info}}</h2>
                        <div class="space-bottom-2x"></div>
                    </div>

                    <!-- Portfolio Filter -->


                    <div id="grid-container" class="cbp-l-grid-masonry">
                        <ul>

                             <!-- Portfolio Item (image and description) -->
                            {%for sub in section.sub_section_set.all%}
                            <li class="cbp-item office cbp-l-grid-masonry-height1">
                                <a class="cbp-caption cbp-lightbox" data-title="Office" href="{{sub.img.url}}">
                                    <div class="cbp-caption-defaultWrap">
                                        <img src="{{sub.img.url}}" alt="">
                                    </div>
                                    <div class="cbp-caption-activeWrap">
                                        <div class="cbp-l-caption-alignCenter">
                                            <div class="cbp-l-caption-body">
                                                <div class="cbp-l-caption-title">{{object.info}}</div>
                                                <!--<div class="cbp-l-caption-desc">2012/02</div>-->
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            {%endfor%}
                        </ul>
                    </div>
                </div><!-- /row -->
            </div><!-- /container -->
            <!-- End Projects -->
        <!-- Footer -->
        <div class="footer-big">
            <div class="container">
                <div class="row">

                    <!-- About Us Information -->
                    <div class="col-md-3 col-sm-6">
                        <div class="f-logo">
                            <h2>Our<br>Offices</h2>
                        </div>
                    </div>

                    <!-- Recent Posts -->


                    <!-- Latest Tweet -->


                    <!-- Recent Works -->
                    <div class="col-md-6 col-sm-6 f-inner">
                        <div class="col-sm-1">
                            <i class="fa fa-map-marker fa-lg"></i>
                        </div>
                        <div class="col-sm-11">
                            <strong>Nigeria</strong>
                            <div class="f-space"></div>
                           <address>
                                45ss beside Stadium Gate, School Rd, Umuahia<br>
                                    Abia State- RN-1857056           <br>
                                    <abbr title="Phone">P:</abbr> 08139980010 <br/>
                                    <abbr title="Phone">M:</abbr> 09033225454 <br/>
                                    vizidgroups@gmail.com<br/>
                                    MarviesSoftTech@gmail.com
                            </address>
                        </div>
                    </div>

                       <div class="col-md-3 col-sm-6">
                        <div class="f-logo">
                          <img src="{%static 'display/img/logo.jpg'%}" width="167" height="82">
                            </div>
                    </div>


                </div>
            </div>
        </div>

        <div id="footer">
            <div class="container">
                <div class="row">
                    <!-- Copyright -->
                    <div class="col-sm-6 col-md-6 f-copyright">
                        <span>© Copyright  - All Rights Reserved</span>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <!-- Social Icons -->
                        <ul class="footer-social">
                            <li><a href="https://wa.me/09033225454"><span class="fa-stack fa-lg"></span><img height="40px" src="{%static 'display/img/about/whatsapp.png'%}"></a></li>
                            <li><a href="https://instagram.com/vizid_decors?iqshid=YmMyMTA2M2Y="><span class="fa-stack fa-lg"></span><img height="40px" src="{%static 'display/img/about/instagram.jpeg'%}"></a></li>
                            <li><a href="https://m.facebook.com/vizidcutie/"><span class="fa-stack fa-lg"></span><img height="40px" src="{%static 'display/img/about/facebook.png'%}"></a></li>

                        </ul>
                    </div>
                </div><!-- /row -->
            </div><!-- /container -->
        </div>
        <!-- End Footer -->

 <!-- jQuery Plugins -->
        <script src="{%static 'display/js/jquery-1.11.1.min.js'%}" ></script>
        <script src= "{%static 'display/js/bootstrap.min.js'%}"></script>
        <script src="{%static 'display/js/jquery.themepunch.tools.min.js'%}"></script>
        <script src="{%static 'display/js/jquery.themepunch.revolution.min.js'%}"></script>
        <script src="{%static 'display/js/jquery.cubeportfolio.min.js'%}" ></script>
        <script src= "{%static 'display/js/owl.carousel.js'%}"></script>
        <script src="{%static 'display/js/moderniz.js'%}"></script>
        <script src= "{%static 'display/js/jquery.sticky.js'%}"></script>
        <script src="{%static 'display/js/jquery.mmenu.min.js'%}"></script>
       <!--  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>      -->
        <script src= "{%static 'display/js/app.js'%}"></script>
</body>
</html>